title:            samesense blog
tagline:          A short tagline
description:      A web log about my journey through the trenches of computational biology
#url:              http://prakhar1989.github.io
#url:              http://localhost:4000
url:              http://samesense.github.io/

# Owner/author information
owner:
  name:           Perry Evans
  avatar:         mugshot-001.jpg
  bio:            "Computational biologist at a children's hospital"
  github:         samesense
  linkedin:       perry-evans
#  twitter:	  @oncolytic

# Analytics and webmaster tools stuff goes here
#google_analytics:  UA-40692332-1

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Projects
    url: /projects/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highligher:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
